### ISSUE TITLE
打包访问不到静态文件的问题

### ISSUE THREAD

**Issue by reihs-c** [zxiaogong/ssr-express-vue3#1]
在server.ts里面添加 app.use(express.static('dist/client'))

**Comment by zxiaogong** [comment]
方便给个联系方式，截图我看下吗？&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月8日(星期四) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zxiaogong/ssr-express-vue3] 打包访问不到静态文件的问题 (Issue #1)





 
在server.ts里面添加 app.use(express.static('dist/client'))

**Comment by zxiaogong** [comment]
运行三个打包指令完成后，你需要在 dist/client/index.html 中修改下静态文件的路径。(暂时还找不到其他解决方法，只能每次打包后手动修改)
![image](https://user-images.githubusercontent.com/110887292/206354000-b373aceb-21af-44d1-bb60-1a6c19859767.png)
